build-example:
	nasm -f bin boot_sector_simple.asm -o boot_sector_simple.bin

build-hello:
	nasm -f bin boot_sector_hello.asm -o boot_sector_hello.bin

build-stack:
	nasm -f bin boot_sector_stack.asm -o boot_sector_stack.bin